version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            pip install pytest
      - run: 
          name: Run Unit Tests
          command: |
            pytest app/testunit01.py 
          
workflows:
  build_test:
    jobs:
     - run_tests
